config/routes.rb
Rails.application.routes.draw do
  get '/pages/info'

  root :to => redirect('/ideas')
  resources :kims
  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/kim.rb
class Kim < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/kims_controller.rb
class KimsController < ApplicationController
  before_action :set_kim, only: [:show, :edit, :update, :destroy]

  # GET /kims
  # GET /kims.json
  def index
    @kims = Kim.all
  end

  # GET /kims/1
  # GET /kims/1.json
  def show
  end

  # GET /kims/new
  def new
    @kim = Kim.new
  end

  # GET /kims/1/edit
  def edit
  end

  # POST /kims
  # POST /kims.json
  def create
    @kim = Kim.new(kim_params)

    respond_to do |format|
      if @kim.save
        format.html { redirect_to @kim, notice: 'Kim was successfully created.' }
        format.json { render :show, status: :created, location: @kim }
      else
        format.html { render :new }
        format.json { render json: @kim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kims/1
  # PATCH/PUT /kims/1.json
  def update
    respond_to do |format|
      if @kim.update(kim_params)
        format.html { redirect_to @kim, notice: 'Kim was successfully updated.' }
        format.json { render :show, status: :ok, location: @kim }
      else
        format.html { render :edit }
        format.json { render json: @kim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kims/1
  # DELETE /kims/1.json
  def destroy
    @kim.destroy
    respond_to do |format|
      format.html { redirect_to kims_url, notice: 'Kim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kim
      @kim = Kim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kim_params
      params.require(:kim).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/kims_helper.rb
module KimsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to '', idea, :class=>"glyphicon glyphicon-eye-open iconsize" %></td>
        <td><%= link_to '', idea, :class=>"glyphicon glyphicon-scissors iconsize" %></td>
        <td><%= link_to '', idea,  method: :delete, data: { confirm: 'Are you sure?' }, :class=> "glyphicon glyphicon-trash iconsize" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>Actualmente hay <%= Idea.count %> ideas activas </p>
<!-- <span  class="glyphicon glyphicon-tree-deciduous" aria-hidden="true"></span> -->
<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width=>450) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/kims/_form.html.erb
<%= form_for(@kim) do |f| %>
  <% if @kim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kim.errors.count, "error") %> prohibited this kim from being saved:</h2>

      <ul>
      <% @kim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kims/edit.html.erb
<h1>Editing Kim</h1>

<%= render 'form' %>

<%= link_to 'Show', @kim %> |
<%= link_to 'Back', kims_path %>

app/views/kims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kims</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kims.each do |kim| %>
      <tr>
        <td><%= kim.name %></td>
        <td><%= kim.description %></td>
        <td><%= kim.picture %></td>
        <td><%= link_to 'Show', kim %></td>
        <td><%= link_to 'Edit', edit_kim_path(kim) %></td>
        <td><%= link_to 'Destroy', kim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kim', new_kim_path %>

app/views/kims/new.html.erb
<h1>New Kim</h1>

<%= render 'form' %>

<%= link_to 'Back', kims_path %>

app/views/kims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kim.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @kim.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @kim.picture %>
</p>

<%= link_to 'Edit', edit_kim_path(@kim) %> |
<%= link_to 'Back', kims_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <!-- Latest compiled and minified CSS -->

<!-- Latest compiled and minified JavaScript -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(ideas_path) %>">
          <%= link_to 'Ideas', ideas_path %>
        </li>
        <li class="<%= 'active' if current_page?(pages_info_path) %>">
          <%= link_to 'Quien soy?', pages_info_path %>
        </li>
        <li class="<%= 'active' if current_page?(new_idea_path) %>">
          <%= link_to 'Nueva Idea', new_idea_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
<%= yield %>
</div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<footer>
  <div class="container">
    Rails Girls 2016
  </div>
</footer>
<script src="https://maxcdn.boothstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<h1>Cambio Climatico</h1>
<h2>Definicion</h2>
<p>El cambio climático es un cambio en la distribución estadística de los patrones meteorológicos durante un periodo prolongado de tiempo (décadas a millones de años). Puede referirse a un cambio en las condiciones promedio del tiempo o en la variación temporal meteorológica de las condiciones promedio a largo plazo (por ejemplo, más o menos fenómenos meteorológicos extremos). Está causado por factores como procesos bióticos, variaciones en la radiación solar recibida por la Tierra, tectónica de placas y erupciones volcánicas. También se han identificado ciertas actividades humanas como causas significativas del cambio de clima reciente, a menudo llamado calentamiento global</p>